### ISSUE TITLE
Release 8.1.0 breaks server startup

### ISSUE THREAD

**Issue by rtyley** [guardian/play-secret-rotation#449]
Unfortunately [v8.1.0](https://github.com/guardian/play-secret-rotation/releases/tag/v8.1.0), broke server startup, and should not be used. The release contained this single change:

* https://github.com/guardian/play-secret-rotation/pull/447

The error only occurs when Play is run in 'production' mode - typically, when we run Play as developers, we run Play in 'dev' mode, with the `run` command - in this mode, you have things like hot-code-reload, and the application-secret checks are more lenient. However, those behaviours aren't desirable in Production, so when a Play app is deployed, we get those additional checks.

We can simulate Production behaviour in dev by running with [`runProd`](https://www.playframework.com/documentation/3.0.x/Deploying#Running-a-test-instance) rather than `run`, eg, for Ophan:

```
sbt ";project dashboard ;runProd"
```

The error given is:

```
Oops, cannot start the server.
Configuration error: Configuration error[
The application secret has not been set, and we are in prod mode. Your application is not secure.
To set the application secret, please read https://playframework.com/documentation/latest/ApplicationSecret
]
	at play.api.Configuration$.$anonfun$configError$1(Configuration.scala:159)
	at scala.Option.map(Option.scala:242)
	at play.api.Configuration$.configError(Configuration.scala:151)
	at play.api.Configuration.reportError(Configuration.scala:410)
	at play.api.http.HttpConfiguration$.getSecretConfiguration(HttpConfiguration.scala:283)
	at play.api.http.HttpConfiguration$.fromConfiguration(HttpConfiguration.scala:228)
	at play.api.BuiltInComponents.httpConfiguration(Application.scala:272)
	at play.api.BuiltInComponents.httpConfiguration$(Application.scala:271)
	at play.api.BuiltInComponentsFromContext.httpConfiguration$lzycompute(ApplicationLoader.scala:229)
	at play.api.BuiltInComponentsFromContext.httpConfiguration(ApplicationLoader.scala:229)
	at configuration.ApplicationComponents.<init>(ApplicationComponents.scala:136)
	at configuration.DashboardApplicationLoader.load(DashboardApplicationLoader.scala:20)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:28)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

**Comment by mkurz** [comment]
8.0.0 works? I can't see from the referenced PR why 8.1.0 would fail...

**Comment by rtyley** [comment]
> 8.0.0 works? I can't see from the referenced PR why 8.1.0 would fail...

Yep, it is surprising! I intend to investigate the cause as soon as possible today, I'm afraid that PR https://github.com/guardian/play-secret-rotation/pull/447 may hide some changes in it's diff - for instance, for `Configuration`, it uses `withFallback` rather than `++`, tho' I haven't had time yet to check if that does something to the laziness of evaluation. Will find out soon...
